name: 'Eslint Check (Node.js)'

on:
    push:
    pull_request_review_comment:

jobs:
    build:
        runs-on: 'ubuntu-latest'
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 18
                cache: 'npm'
            
            - name: Install Needed Dependencies
              id: install-dependencies
              run: npm install
            
            - name: Run Check
              id: eslint-check
              run: npm run check